name: File Transform JSON

on:
  workflow_call:
    inputs:
      workingDirectoryToTransform:
        required: true
        type: string 
      fileTotransform:
        required: true
        type: string 
        default: 'appsettings.json'

jobs:
  transform-json:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Config File Before Transformation
        run: type "${{ github.event.inputs.fileTotransform }}"
        working-directory: ${{ github.event.inputs.workingDirectoryToTransform }}
        shell: powershell

      - name: Transform JSON File with Environment Variables
        run: |
          $jsonPath = "${{ github.event.inputs.fileTotransform }}"
          $fullPath = Join-Path -Path $PWD -ChildPath $jsonPath
          $json = Get-Content $fullPath | ConvertFrom-Json

          foreach ($property in $json.PSObject.Properties) {
            $envValue = $env:$($property.Name)
            if ($envValue) {
              $json.$($property.Name) = $envValue
            }
          }

          $json | ConvertTo-Json -Depth 10 | Set-Content $fullPath
        working-directory: ${{ github.event.inputs.workingDirectoryToTransform }}
        shell: powershell

      - name: Print Config File After Transformation
        run: type "${{ github.event.inputs.fileTotransform }}"
        working-directory: ${{ github.event.inputs.workingDirectoryToTransform }}
        shell: powershell
